version: '3.5'

services:
  mysql:
    image: mysql:5.7.29
    container_name: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./devbox/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./devbox/mysql/data:/var/lib/mysql/:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qwe123!"

  # redis:
  #   image: redis:5.0.3-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./devbox/redis/redis.conf:/etc/redis.conf:ro
  #     - ./devbox/redis/data:/data/:rw
  #   restart: always
  #   entrypoint: ["redis-server", "/etc/redis.conf"]
  #   networks:
  #     - backend


volumes:
  mysql: